"""Initial migration

Revision ID: 32dc0da3388e
Revises: 
Create Date: 2024-11-13 11:17:48.060322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dc0da3388e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_USER',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USUARIO', sa.String(length=120), nullable=False),
    sa.Column('SENHA', sa.String(length=129), nullable=False),
    sa.Column('ADMIN', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('USUARIO')
    )
    op.create_table('TB_NOTICIA_RASPADA',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('LINK_ID', sa.String(length=64), nullable=False),
    sa.Column('URL', sa.String(length=1000), nullable=False),
    sa.Column('FONTE', sa.String(length=250), nullable=False),
    sa.Column('DATA_PUBLICACAO', sa.DateTime(), nullable=True),
    sa.Column('CATEGORIA', sa.String(length=50), nullable=False),
    sa.Column('QUERY', sa.String(length=250), nullable=True),
    sa.Column('ID_ORIGINAL', sa.String(length=2000), nullable=False),
    sa.Column('DT_RASPAGEM', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DT_DECODE', sa.DateTime(), nullable=True),
    sa.Column('TITULO', sa.String(length=250), nullable=True),
    sa.Column('ID_USUARIO', sa.Integer(), nullable=True),
    sa.Column('STATUS', sa.String(length=25), nullable=True),
    sa.Column('TEXTO_NOTICIA', sa.Text(), nullable=True),
    sa.Column('LINK_ORIGINAL', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['ID_USUARIO'], ['TB_USER.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('LINK_ID')
    )
    op.create_index(op.f('ix_TB_NOTICIA_RASPADA_ID'), 'TB_NOTICIA_RASPADA', ['ID'], unique=False)
    op.create_table('TB_NOTICIA_RASPADA_NOME',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('NOTICIA_ID', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('CPF', sa.String(length=14, collation='utf8mb4_unicode_ci'), server_default='0', nullable=True),
    sa.Column('NOME_CPF', sa.String(length=100, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('APELIDO', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('SEXO', sa.String(length=1, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('PESSOA', sa.String(length=2, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('IDADE', sa.Integer(), nullable=True),
    sa.Column('ATIVIDADE', sa.String(length=140, collation='latin1_general_ci'), nullable=True),
    sa.Column('ENVOLVIMENTO', sa.String(length=500, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('TIPO_SUSPEITA', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('FLG_PESSOA_PUBLICA', sa.String(length=1, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ANIVERSARIO', sa.Date(), nullable=True),
    sa.Column('INDICADOR_PPE', sa.String(length=1, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['NOTICIA_ID'], ['TB_NOTICIA_RASPADA.ID'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_TB_NOTICIA_RASPADA_NOME_ID'), 'TB_NOTICIA_RASPADA_NOME', ['ID'], unique=False)
    op.create_index(op.f('ix_TB_NOTICIA_RASPADA_NOME_NOTICIA_ID'), 'TB_NOTICIA_RASPADA_NOME', ['NOTICIA_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TB_NOTICIA_RASPADA_NOME_NOTICIA_ID'), table_name='TB_NOTICIA_RASPADA_NOME')
    op.drop_index(op.f('ix_TB_NOTICIA_RASPADA_NOME_ID'), table_name='TB_NOTICIA_RASPADA_NOME')
    op.drop_table('TB_NOTICIA_RASPADA_NOME')
    op.drop_index(op.f('ix_TB_NOTICIA_RASPADA_ID'), table_name='TB_NOTICIA_RASPADA')
    op.drop_table('TB_NOTICIA_RASPADA')
    op.drop_table('TB_USER')
    # ### end Alembic commands ###
