"""Alterar colunas para Boolean

Revision ID: 4ad155ca86d2
Revises: 
Create Date: 2024-10-29 13:01:34.915960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ad155ca86d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Convert existing data if necessary
    op.execute("""
        UPDATE TB_NOTICIA_RASPADA_NOME
        SET FLG_PESSOA_PUBLICA = CASE FLG_PESSOA_PUBLICA WHEN '1' THEN TRUE ELSE FALSE END,
            INDICADOR_PPE = CASE INDICADOR_PPE WHEN '1' THEN TRUE ELSE FALSE END
    """)
    # Alter the column types
    op.alter_column('TB_NOTICIA_RASPADA_NOME', 'FLG_PESSOA_PUBLICA',
                    existing_type=sa.String(length=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('TB_NOTICIA_RASPADA_NOME', 'INDICADOR_PPE',
                    existing_type=sa.String(length=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_NOTICIA_RASPADA_NOME',
    sa.Column('ID', mysql.BIGINT(display_width=15), autoincrement=True, nullable=False),
    sa.Column('NOTICIA_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('NOME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('CPF', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=14), server_default=sa.text("'0'"), nullable=True),
    sa.Column('NOME_CPF', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('APELIDO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('SEXO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('PESSOA', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('IDADE', mysql.DECIMAL(precision=3, scale=0), nullable=True),
    sa.Column('ATIVIDADE', mysql.VARCHAR(charset='latin1', length=140), nullable=True),
    sa.Column('ENVOLVIMENTO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('TIPO_SUSPEITA', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('FLG_PESSOA_PUBLICA', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('ANIVERSARIO', sa.DATE(), nullable=True),
    sa.Column('INDICADOR_PPE', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['NOTICIA_ID'], ['TB_NOTICIA_RASPADA.ID'], name='fk_TB_NOTICIA_RASPADA_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_NOME', 'TB_NOTICIA_RASPADA_NOME', ['NOME'], unique=False)
    op.create_index('fk_TB_NOTICIA_RASPADA_1_idx', 'TB_NOTICIA_RASPADA_NOME', ['NOTICIA_ID'], unique=False)
    # ### end Alembic commands ###
